### ISSUE TITLE
Script update

### ISSUE THREAD

**Issue by blindpet** [HazCod/Gunther#11]
Got a few errors, good idea to add mkdir -p to the bash script to avoid these (the file exists are because i reran the script so you can ignore those):

mkdir: cannot create directory `/var/www': File exists
fatal: destination path '/var/www' already exists and is not an empty directory.
mkdir: cannot create directory`/var/www/webdav': File exists
setup.sh: line 49: /etc/nginx/webdav.auth: No such file or directory
mkdir: cannot create directory `/etc/nginx/ssl-certs': No such file or directory
mkdir: cannot create directory`/var/log/nginx': File exists
setup.sh: line 59: cd: /etc/nginx/ssl-certs: No such file or directory

And after later this error

setup.sh: line 157: /etc/nginx/conf/nginx.conf: No such file or directory

I tried this on the banana Pi and a VM with Ubuntu and same errors

**Comment by hazcod** [comment]
Thanks for the feedback, changed that in commit 311eecac4b7aa805bcce447ea84b0a7fd9277e2c.

The 'no such file or directory' errors are quite weird, as the directories should be created by default. Maybe because of your fiddling? idk.

Lemme know how it goes now

**Comment by blindpet** [comment]
Will check later but I think it is an issue with building from source that it is not creating the necessary folders, I would consider adding a repo

http://nginx.org/en/linux_packages.html

**Comment by hazcod** [comment]
I dislike the source building too, but it is needed as the webdav module is not included by default in the nginx installation. (aswell as digest authentication)

**Comment by blindpet** [comment]
OK, perhaps there is a post script for it like make install-conf or something like that. I didn't even get the init.d script working.

**Comment by hazcod** [comment]
Can you say what exactly didn't work? Errors, warnings, ..

**Comment by blindpet** [comment]
sudo service nginx restart
Usage: {start|stop|restart|force-reload}

And that's it, nginx isn't running, going to the IP or using localhost yields 404 error

**Comment by hazcod** [comment]
and sudo service nginx start ?
Could you pastebin the /etc/init.d/nginx script?

**Comment by blindpet** [comment]
Same result

**Comment by blindpet** [comment]
It may also be an idea to install the nginx package first and then build a new one from source, maybe then the necessary files and folders will be there properly and they are just upgraded?

Wiping VM and will try now

**Comment by blindpet** [comment]
Installed nginx, got a build error when running script http://pastebin.com/qd30zn6F

**Comment by hazcod** [comment]
Ohh, the correct nginx digest-auth fork wasn't included in the script. My apologies, try again

**Comment by blindpet** [comment]
Delete old setup.sh and grabbed the new setup.sh and same errors

**Comment by hazcod** [comment]
Try a rm -r /tmp/\* first

**Comment by blindpet** [comment]
Same error

**Comment by hazcod** [comment]
Are you sure you removed everything in /tmp ? I did the steps in the latest setup.sh and it makes & installs fine.. Try building in a directory in /tmp

**Comment by blindpet** [comment]
cleaned manually and it worked, nginx service still doesn't start though, will wipe one more time and try again

**Comment by hazcod** [comment]
Ahh, could be the init.d script isn't echoed correctly. Pastebin /etc/init.d/nginx if it doesn't work.

**Comment by blindpet** [comment]
just wiped and same init.d error. script is http://pastebin.com/YikzHZQr

**Comment by hazcod** [comment]
For some reason, line 27 has removed the $1; `case "" in` should be `case "$1" in`

**Comment by hazcod** [comment]
Fixed in d47029b0372090822a818e232e8bfd98d186a7d4 :-)

**Comment by blindpet** [comment]
New error
Starting nginx: nginx: [emerg] unexpected "}" in /etc/nginx/conf/nginx.conf:67

**Comment by hazcod** [comment]
Strange, I don't see how that could be an error

**Comment by blindpet** [comment]
Removed the init.d and emptied /tmp, same unexpected "}" error

**Comment by hazcod** [comment]
Could you pull and try again? Stupid quotes fixes in 18322af3000ca2fce11f0317392711885877a77e.
