### ISSUE TITLE
Fix Stream keeping browser busy

### ISSUE THREAD

**Issue by hazcod** [HazCod/Gunther#16]
VideoStream or VideoJS issue?

**Comment by hazcod** [comment]
EDIT: Only on movie streaming, not on show streaming.

**Comment by blindpet** [comment]
It also means that when you try to click Series you get a gateway timeout error

**Comment by hazcod** [comment]
Yup, still need to look up why this is happening tough

**Comment by hazcod** [comment]
Switch to RTMP should improve performance and this issue.
Downside: it's not over SSL.

**Comment by blindpet** [comment]
Just tested this and I get gateway timeouts when playing a movie and clicking Dashboard

**Comment by hazcod** [comment]
Yah, sorry @blindpet. I kinda screwed up and commited dev work to master.
It's being researched

**Comment by hazcod** [comment]
I am glad to say this was fixed in b9dc762847cefae351870e343c8be49a70b2a0e0
