### ISSUE TITLE
Setup script corrections

### ISSUE THREAD

**Issue by stephenl03** [HazCod/Gunther#18]
I had to change line 1 from `#!/bin/sh` to `#!/bin/bash` so the script wouldn't error when it got to line 50.
In order for me to get the ADMIN_PASSWORD variable to work with my admin password I had to change the variable line to... 
`ADMIN_PASSWORD='my_password_with_$p3cial_characters'`
Also at the end of line 137 there is a missing `;`

**Comment by hazcod** [comment]
Thank you! Corrected in 87f7ce5d8a05ee37ea1a7e01b403da03beeb2616.
