### ISSUE TITLE
Apache and multiple instances

### ISSUE THREAD

**Issue by blindpet** [HazCod/Gunther#19]
I'm very glad nginx is being used, I have an admin that wants to run multiple vhosts of your project on the same machine but he only uses Apache2, you used to use apache2 with this project, do you still have the vhost configuration?

Also which db system do you use now?

**Comment by hazcod** [comment]
I am no longer using a database, but file caching and the webdav authentication file.

**Comment by blindpet** [comment]
Can you provide the old Apache vhost config?

**Comment by hazcod** [comment]
Ahh, sorry, forgot to post: https://github.com/HazCod/Gunther/commit/0531f195d916087e82331a419461f9e4d9114f36

**Comment by blindpet** [comment]
Thank you very much

**Comment by blindpet** [comment]
btw if you have a setupapache.sh script laying around you are welcome to add it ;)

**Comment by hazcod** [comment]
Nope, sorry, but shouldn't be too hard to set it up
