### ISSUE TITLE
setup.sh issue

### ISSUE THREAD

**Issue by blindpet** [HazCod/Gunther#24]
Trying to do new tests and after running setup.sh getting these errors when trying to go into the Gunther site, installing php-pear didn't help
`Warning: require_once(application/config.php): failed to open stream: No such file or directory in /var/www/index.php on line 24`

`Fatal error: require_once(): Failed opening required 'application/config.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/index.php on line 24`

**Comment by blindpet** [comment]
On a sidenote since you build a custom nginx from scratch consider adding these lines to speed up compiling by using all cores

cpunum=$(nproc)

make -j$cpunum

**Comment by hazcod** [comment]
Ahh, somehow the config.php did not get through in the repo. fixed.
Thanks for the cpu core suggestion, added in f4e98efb96be00e0d5a0bce0259cef91a1f9a584.

**Comment by blindpet** [comment]
Started fresh and same error:

The setup.sh is giving these errors as well

`rm: cannot remove `nginx-*': No such file or directory
chmod: cannot access `/var/log/nginx.error.log': No such file or directory`

Sorry looks ok now after  I deleted the /var/www folder
