### ISSUE TITLE
Image poster size skewed

### ISSUE THREAD

**Issue by blindpet** [HazCod/Gunther#25]
Noticed images are not scaled properly, here is an example http://i.imgur.com/wRpNvmp.png

**Comment by hazcod** [comment]
Might be my leet CSS skills :-1:

**Comment by blindpet** [comment]
Sickrage uses 212x311 so just try to keep that ratio. This isn't too important, would love for the CP and SR videos to play in Gunther more than anything ;)

**Comment by blindpet** [comment]
The series posters are showing normally btw so it is just movie posters

**Comment by hazcod** [comment]
Removed height attribute in 80cab7fd6ef9256dc0be3742196f06d22a4a3268.
This was because not all posters are the same size
