### ISSUE TITLE
SickRage shows not showing episodes

### ISSUE THREAD

**Issue by blindpet** [HazCod/Gunther#26]
Gunther is showing the shows in the SickRage database but it is not showing the episodes despite a cache flush and library refresh from Gunther's admin panel.

The shows in Sickrage have been post processed and are showing as downloaded.

The folder structure I am using is Show name/Season/episodename

**Comment by hazcod** [comment]
Is this still an issue?

**Comment by blindpet** [comment]
Yes, even with the cache flushes etc no change.

**Comment by hazcod** [comment]
Try restarting Sickrage and doing a force clear cache. (right upper hand in admin panel)

Gunther only reads from the API so either it gets all episodes or none.

**Comment by blindpet** [comment]
Just flushed, restarted and refreshed, no dice.

**Comment by hazcod** [comment]
Could you add following line in `/var/www/application/includes/MediaModel.php` on line 275;

```
        public function getEpisode($serie_id, $season_id, $episode_id){
            $json = $this->getJson($this->settings['SB_API'] . 'episode&tvdbid=' . urlencode($serie_id) . '&season=' . $season_id . '&episode=' . $episode_id . '&full_path=1');
                 error_log(var_dump($json)); #ADD THIS LINE
            if ($json && count((array)$json->data)){
                return $json->data;
            } else {
                return false;
            }
        }
```

Reload episodes and pastebin the log please.

**Comment by blindpet** [comment]
http://pastebin.com/rQ5gkCTR

**Comment by hazcod** [comment]
All episodes are set to skipped, so why would they appear in Gunther?

**Comment by blindpet** [comment]
Not all, I grabbed one episode for each of them. After adding those lines I did see some episode thumbs at the bottom but when I click them I get another error, unfortunately the thumbnails are gone and I didn't catch the error.

**Comment by hazcod** [comment]
The SickRage API reports that all episodes for that show are set to skipped, so I can't do anything with that I'm afraid. I can only use what the API gives me

**Comment by blindpet** [comment]
It looks like it is not showing the entire show. I am grabbing an episode from the list that did show up now, will post new logs if applicable soon.

**Comment by blindpet** [comment]
Here is one from GoT where the season finale is definitely there http://pastebin.com/8p5vGyq8

**Comment by blindpet** [comment]
I think it may have been the crazy slow SickRage, now the episode is found but still can't play

http://pastebin.com/pC0zQkzN

I had to add an episode for season 2, are you sure it parses all the output from SR? I can see when i go to copy the errors it looks like output is further up that I can't reach.

**Comment by hazcod** [comment]
The full log is available at `/var/log/nginx/errors.log`

**Comment by blindpet** [comment]
That isn't showing the specific series errors, there are a lot of blank lines like this though:

PHP message: 
PHP message: 
PHP message:

**Comment by hazcod** [comment]
If it isn't in /var/log/nginx/errors.log, then the error does not exist. The log interface in the admin area reads from this file.

**Comment by hazcod** [comment]
It seems I skipped over some code when fixing up the numbering. Please try again now. (2abb3b9f98a168d210b3d88b23d3f400cf1093dd)

**Comment by blindpet** [comment]
It did the same thing again, when I did a git pull and went to series it did show added episode thumbnails at the bottom of the page but when I go in to the individual series they still aren't showing.

The one episode it does find is still throwing the episode not found error

http://pastebin.com/tvq5AgPW

Should I open separate ticket for SR videos not playing?

**Comment by hazcod** [comment]
Can you post the log when editing `/var/www/application/includes/MediaModel.php` again please?
Or try another serie. So vague :/

**Comment by blindpet** [comment]
I'm guessing you get the best data if I do another series and add the code to mediamode1.php so I am doing that and will pastebin it for you shortly

**Comment by blindpet** [comment]
OK the other show I'm trying SickRage is having a tough time finding, for now I have redone the maid one with the log from the series page itself and the admin page log file. There still seems to be these PHP blank line errors in the log before I cleared it to produce this log. Also this thing about the episodes showing at the bottom of Gunther and then disappearing makes me think they are just not sticking

http://pastebin.com/PswF8nFH

**Comment by HazCod** [comment]
Pretty strange, if you look at the following you'll see that the status is 'Downloaded', but no path is given;
```
object(stdClass)#56 (3) {
  ["data"]=>
  object(stdClass)#21 (10) {
    ["airdate"]=>
    string(10) "2014-07-13"
    ["description"]=>
    string(355) "When Nick finally admits his secret to Marisol, she convinces him to make things right with all those involved. Carmen meets a handsome stranger who offers to help her with her music career. As Zoila waivers between Pablo and Javier, she gets some shocking news. Valentina is offered the opportunity of a lifetime. Spence and Rosie decide to tie the knot."
    ["file_size"]=>
    int(318673871)
    ["file_size_human"]=>
    string(9) "303.91 MB"
    ["location"]=>
    string(80) "/home/pi/Devious Maids/Season 02/Devious Maids - S02E13 - Look Back in Anger.mp4"
    ["name"]=>
    string(18) "Look Back in Anger"
    ["quality"]=>
    string(4) "SDTV"
    ["release_name"]=>
    string(35) "Devious.Maids.S02E13.HDTV.x264-ASAP"
    ["status"]=>
    string(10) "Downloaded"
    ["subtitles"]=>
    string(0) ""
  }
  ["message"]=>
  string(0) ""
  ["result"]=>
  string(7) "success"
}
```

**Comment by blindpet** [comment]
The path is here, isn't it?

`````` ["location"]=>
    string(80) "/home/pi/Devious Maids/Season 02/Devious Maids - S02E13 - Look Back in Anger.mp4"```
``````

**Comment by hazcod** [comment]
Yup, is it available from the machine?

**Comment by blindpet** [comment]
It is on the machine yes, here is what I was talking about, it found new episodes http://i.imgur.com/lvhfpEV.png

When I click on any of them I get episode not found with this error in logs http://pastebin.com/vMcSGBKK

When I go to the individual series page those updated episodes aren't there that it shows in the screenshot

**Comment by hazcod** [comment]
Can you try again now? It may show episodes that were snatched, but now downloaded yet.
b419de365c060641f2d972c9e7e2fa90c1d2d0d3

~~(as always, clear cache)~~

**Comment by blindpet** [comment]
Same issue, nothing showing in each individual series except for that one episode it did manage to add, the other 4 are just lost.

**Comment by hazcod** [comment]
I'll check further next week, thanks for the help so far

**Comment by blindpet** [comment]
Happy to help, it's a very cool and unique project :) Would love to see sonarr support next (do not use my installer for sonarr since it installs an arm version of mono), I think they have a decent API.

**Comment by hazcod** [comment]
Yah, biggest thing is that I don't use Sonarr myself (subtitles, torrent) and current code has the providers hardcoded.
First we'll make sure everything works as planned, then I'll see about Sonarr

**Comment by hazcod** [comment]
Closed until after refactoring. Re-open if it still persists.
