### ISSUE TITLE
Find a way to steam with PHP

### ISSUE THREAD

**Issue by qantourisc** [HazCod/Gunther#27]
Not sure where else to put this. So made you an issue.

Would this work ? http://stackoverflow.com/questions/432713/serving-large-files-with-php

**Comment by hazcod** [comment]
Well, actually I am already using chunks to stream; https://github.com/HazCod/Gunther/blob/master/application/includes/VideoStream.php#L12

**Comment by hazcod** [comment]
The problem, AFAIK, is that the PHP code does not detect that the user aborted the download or so.

**Comment by hazcod** [comment]
Not necessary anymore, fixed in b9dc762847cefae351870e343c8be49a70b2a0e0.
