### ISSUE TITLE
setupDownloaders.sh error

### ISSUE THREAD

**Issue by blindpet** [HazCod/Gunther#28]
Just pulled the new update and saw you are replacing rather than appending, >> instead of >

`echo "HP_USER=media" > /etc/default/headphones
echo "HP_HOME=/home/media/headphones" > /etc/default/headphones
echo "HP_PORT=/home/media/headphones" > /etc/default/headphones
echo "SSD_OPTS=--group=media" > /etc/default/headphones`

Edit: Saw you're editing them ;)

**Comment by hazcod** [comment]
Thanx for noticing, I did too!
