### ISSUE TITLE
SQL Script error

### ISSUE THREAD

**Issue by blindpet** [HazCod/Gunther#5]
I run mysql -u root -p < setup_database.sql

ERROR 1192 (HY000) at line 3: Unknown system variable 'search_path'

**Comment by hazcod** [comment]
Try ommitting the 'set search_path to' line and can you try again?

**Comment by hazcod** [comment]
Edit: Should be fixed in 03b667fb234fdbb1c4c65b7c32da77a825169595 and db5db076e97f67f48228207ca7d4c78d88a706c5 . 
My apologies!
