### ISSUE TITLE
PosgreSQL Errors

### ISSUE THREAD

**Issue by blindpet** [HazCod/Gunther#8]
I have to comment out line 52 and 53 for the sql script to run.

I still get this error in line 54:

ERROR 1064 (42000) at line 54: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(NOW()),
  email TEXT,
  lastseen TIMESTAMP,
  role INT NOT NULL,
  PRIMARY KEY ' at line 5

**Comment by hazcod** [comment]
1. You need to create the database, disconnect then connect to 'gunther' on postgresql.
2. What if you use NOW() instead of DEFAULT(NOW()) ? I'm testing this.

EDIT: What is the PosgreSQL version you are using? This works in a SQLfiddle; http://sqlfiddle.com/#!15/1c8ad

**Comment by hazcod** [comment]
Wait, your first post mentions 'check the manual that corresponds to your MySQL server version for the right syntax to use near '(NOW()),'.  Why does it say 'MySQLserver'?

**Comment by blindpet** [comment]
I did not have postgresql installed (thought it did it by default with sql packages). Still getting same error but that is probably because I am trying to run a psql script using the sql client. I think it would be a good idea to create these scripts separately. I will now go search for how to run psql scripts as it seems a bit different

**Comment by hazcod** [comment]
OK, good idea. To be honest, I just copy-pasted it into a psql -d gunther session .
So first switch to the postgres user `su - postgres` and open a default session `psql`, add the datbase gunther by `create database gunther;` and disconnect. (\q or CTRL+D)

Then `psql -d gunther` and the rest of the script.

**Comment by blindpet** [comment]
That makes a big difference, it does seem to finally run all the way through now that I separated them but I ran sudo -u postgres psql -a -f setup_psql.sql

I'm still getting the DB.php error though

You are saying I should do this?

sudo -u postgres psql

create database gunther;
\q

sudo -u postgres psql -a -f setup_psql.sql

Cause that seems to work but still get the DB.php error

config.php still has the correct root password for mysql

**Comment by hazcod** [comment]
You mean the prepare() error? hm.

Be advised, config.php password should be the password you supplied in the setup SQL script.

**Comment by blindpet** [comment]
Yea I mean the prepare() error. I have used the same generic password in all scripts. Do you mean the sql or psql script specifically? I only see a password in the psql script (which is the same in the config.php)

**Comment by hazcod** [comment]
The MySQL script has a `<PASSWORD>` reference too btw.

What does the SQL error say? It's usually above the DB.php error in /var/log/apache2/error.log.

EDIT: As it's very late for me, i'll be looking at this again tomorrow evening.

**Comment by blindpet** [comment]
Using nginx, may be a php pdo driver error

2015/02/26 00:56:56 [error] 4428#0: *1 FastCGI sent in stderr: "PHP message: could not find driver
PHP message: PHP Fatal error:  Call to a member function prepare() on a non-object in /var/www/Gunther/system/DB.php on line 52" while reading response header from upstream, client: 192.168.40.100, server: 192.168.40.111, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "192.168.40.111"

**Comment by blindpet** [comment]
OK I got a bit further (pdo driver was issue) but new errors. It seems I am missing the gunther database in either mysql or psql but I just checked and when I try to create the database in either, I get the message that it already exists. EDIT: restarted nginx and resolved this error

2015/02/26 01:22:59 [error] 2684#0: *7 FastCGI sent in stderr: "PHP message: PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at /var/www/Gunther/index.php:2) in /var/www/Gunther/index.php on line 6
PHP message: SQLSTATE[42000] [1049] Unknown database 'gunther'

But now I get this error 

Parse error: syntax error, unexpected end of file in /var/www/Gunther/application/views/_partials/navbar.php on line 64

**Comment by hazcod** [comment]
Hmm, van you paste your navbar.PHP?
Dont have that issue here.

**Comment by blindpet** [comment]
It is the raw file from git, didn't modify anything. Can you try copying it into your working configuration to see if you get the error?

**Comment by hazcod** [comment]
My working directory IS the git repo, but ill try removing and re-adding.

**Comment by hazcod** [comment]
I copied my config, removed my www/ directory and cloned it again in www/. (and copied my config back over). Zero problems..

Can you try re-pulling? And pastebin your navbar.php, config.php and log? (blur out the passwords)

**Comment by blindpet** [comment]
Repulled. password is generic cause it's just for guide purposes

Warning: session_start(): Cannot send session cookie - headers already sent by (output started at /var/www/Gunther/index.php:2) in /var/www/Gunther/index.php on line 6

Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /var/www/Gunther/index.php:2) in /var/www/Gunther/index.php on line 6

Parse error: syntax error, unexpected end of file in /var/www/Gunther/application/views/_partials/navbar.php on line 65

nginx log

2015/02/27 12:06:46 [error] 1462#0: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  session_start(): Cannot send session cookie - headers already sent by (output started at /var/www/Gunther/index.php:2) in /var/www/Gunther/index.php on line 6
PHP message: PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at /var/www/Gunther/index.php:2) in /var/www/Gunther/index.php on line 6
PHP message: PHP Parse error:  syntax error, unexpected end of file in /var/www/Gunther/application/views/_partials/navbar.php on line 65" while reading upstream, client: 192.168.40.100, server: 192.168.40.111, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "192.168.40.111"
2015/02/27 12:06:46 [error] 1462#0: *2 FastCGI sent in stderr: "PHP message: PHP Warning:  session_start(): Cannot send session cookie - headers already sent by (output started at /var/www/Gunther/index.php:2) in /var/www/Gunther/index.php on line 6
PHP message: PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at /var/www/Gunther/index.php:2) in /var/www/Gunther/index.php on line 6
PHP message: PHP Parse error:  syntax error, unexpected end of file in /var/www/Gunther/application/views/_partials/navbar.php on line 65" while reading upstream, client: 192.168.40.100, server: 192.168.40.111, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "192.168.40.111"

php files http://pastebin.com/xesf2rrv

**Comment by hazcod** [comment]
Hmm, quite vague.
'headers already sent' means there has been output before the system can return anything, in most cases an echo or something. Maybe you should try apache2 instead of nginx?

Before switching, check that the nginx equivalent for mod_rewrite (`ngx_http_rewrite_module`) is enabled and short_tags is enabled (should be done in .htaccess automatically).

**Comment by blindpet** [comment]
I got rid of the first 2 errors - it was because I had phpinfo displayed to make sure mdos were enabled.

I am using php5.5 so short tags are enabled by default http://stackoverflow.com/questions/2185320/how-to-enable-php-short-tags

Rewrite is also enabled by default. There is no .htaccess file for nginx.

Tried setting up apache and it doesn't even start despite me stopping nginx

Which version of php are you using?

**Comment by hazcod** [comment]
The default version of php5 installed in debian alongside apache2.

Can you be a bit more precise than 'it doesn't even start'?
/var/log/apache2/error.log

**Comment by blindpet** [comment]
OK, maybe you are on an older PHP version.

I didn't provide the apache2 errors because I still don't plan on using it :P 

I think you should try setting up a VM running Ubuntu or Debian jessie so you are using the latest packages, the end of file error in navbar.php should not be related to rewrite or short tags.

AH00548: NameVirtualHost has no effect and will be removed in the next release /etc/apache2/sites-enabled/gunther.conf:3
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
(13)Permission denied: AH00072: make_sock: could not bind to address [::]:80
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down

**Comment by hazcod** [comment]
My VPS is running debian with all latest stable packages. :)

`(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80`
That's a system configuration issue, so can't really help you there i'm afraid..
(You did run it as root, eh? Only root can bind to those ports.)

I will be re-installing in the near future (upgrade to beefier VPS), so will try the reinstall.

**Comment by blindpet** [comment]
OK, my real VPS has debian but it's only on wheezy not jessie as jessie isn't stable yet, stable Ubuntu has more recent packages than stable debian AFAIK. 
I'm pretty stubborn about using nginx as I will use this guide for Ubuntu, Windows and the Banana Pi and conserving system resources is always ideal anyway. Apache is just too bloated.

Are you with Digital Ocean? I am happy to share my setup guide so far so you can try getting it to work with nginx.

**Comment by hazcod** [comment]
Maybe nginx is indeed a better choice, as the VPS' used for this purpose WILL be low power. 
Makes for more clients eh.

Tomorrow is the VPS renewal date, so ill order the new one tomorrow.
And no, not digital ocean, but transip. (their big storage plan is pretty slick)
And do share your guide!

**Comment by hazcod** [comment]
To follow this up, I have decided to completely abandon the database idea and purely use the htpasswd file. (and switch over to nginx)

This makes a much smaller and easier install.

**Comment by blindpet** [comment]
Awesome, when the changes are ready ping me and I'll start the guide again from scratch with your new configuration.

**Comment by hazcod** [comment]
Not ready yet, still struggling with the rewrite rules & static file loading.
So far; http://pastie.org/private/pn4adccebjxuwlf310xcfq

**Comment by hazcod** [comment]
@blindpet AFAIK, the script is ready. It's not completely hands-free, but should be straight-forward.

**Comment by blindpet** [comment]
May give this a try later, anything I should know or are things commented so I can navigate the script?

**Comment by hazcod** [comment]
In theory, you should just run the script and for time to time it will ask for something interactive.
The script is commented and should be straight-forward. Check it out.

Best way to do it is run the commands separately
